/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package unicapfood;

import unicapfood.Negocio.Clientes.Cliente;
import unicapfood.Negocio.Clientes.GerenciarCliente;

// import static org.junit.jupiter.api.Assertions.*;

class AddCliente {
    
//     @Test void clienteAdd() {
//         GerenciarCliente addtest = new GerenciarCliente();
//         Cliente cliente1 = new Cliente("carol", 0011122233 , "1234");
//         Cliente expected = new Cliente("carol", 0011122233 , "1234");
        
//         assertEquals(cliente1,expected);
//     }
 }
