/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package unicapfood;

import org.junit.jupiter.api.Test;

import unicapfood.Clientes.GerenciarCliente;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        GerenciarCliente classUnderTest = new GerenciarCliente();
        // assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
